CREATE DATABASE CIVIC_HACKATHON_DB;
CREATE SCHEMA CIVIC_HACKATHON_SCHEMA;

CREATE OR REPLACE TABLE NOTICE_RULE
(   
    ID VARCHAR,
    AGENCY VARCHAR,
    ACTION_TYPE VARCHAR,
    SUMMARY VARCHAR,
    IMPORTANT_DATES VARCHAR,
    PUBLIC_INSPECTION_PDF_URL VARCHAR,
    LAST_UPDATED_DATE DATE,
    PUBLICATION_DATE DATE,
    DI_LOAD_DT DATETIME
);

CREATE OR REPLACE FILE FORMAT PIPE_SEPARATED_FF
TYPE = 'CSV'
FIELD_DELIMITER = '|'
SKIP_HEADER = 1
SKIP_BLANK_LINES = True
EMPTY_FIELD_AS_NULL = true
TRIM_SPACE = True;

CREATE OR ALTER STAGE notice_rule_stage;

ALTER TABLE CIVIC_HACKATHON_DB.CIVIC_HACKATHON_SCHEMA.NOTICE_RULE SET STAGE_COPY_OPTIONS = (PURGE = TRUE);